# google api key
google:
  routes:
    api-key: ${GOOGLE_ROUTES_API_KEY}
    base-url: https://routes.googleapis.com
# twilio credentials
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}
  driver-phone-number: ${TWILIO_DRIVER_PHONE_NUMBER}
# served location
location:
  protocol: ${LOCATION_PROTOCOL}
  host: ${LOCATION_HOST}
  port: ${LOCATION_PORT}
